# Start of automatically generated script
# DO NOT EDIT
# This script is automatically generated by gookme
# GOOKME_CLI_VERSION: {{.Version}}
gookme run -t {{.HookType}}
# End of automatically generated script