name: CI Assets Synchronization

on:
  pull_request:

env:
  GO_VERSION: 1.22.4

jobs:
  check-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Golang
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Run check-format script
        run: make assets
      - name: Assert no changes
        run: git diff HEAD --exit-code
  