name: CI Tests

on:
  pull_request:

env:
  GO_VERSION: 1.22.4

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Golang
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Create temporary directory
        run: mkdir -p ${{ github.workspace }}/tmp
      - name: Run Golang tests
        run: go test -coverprofile cover.out -covermode count $(go list -f '{{.Dir}}/...' -m)
        env:
          TMPDIR: ${{ github.workspace }}/tmp
  